apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rickroll-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: k8s.russparmer.local
    http:
      paths:
      - path: /rickroll
        backend:
          serviceName: rickroll-service
          servicePort: 80
